# Learning graphs with ipycytoscape.  Making use of pandas (part 3)

### Goal
The goal of this article/notebook is to approach the creation of graphs using ipycytoscape assuming you are given the data in a tabular form (excel, CSV, google sheet etc) which actually might be relatively frequent.
This article/notebook follows part 1 and part 2.
The example I am basing this article is built upon the previous ones. We are rendering a small European rail network.

## What do you need to know?
You are expected to have basic notions of python programming.
You should have read the previous two notebooks/articles in the series (part 1 and part 2).
You should have notions of pandas.

## Pandas: Another approach
Lets face it, most of the data we manipulate is somehow stored in a tabular manner. Excel is certainly and by far the most use data manipulation tool in the planet.

I would like you to imagine that the graph that is going to be built in this notebook is real part of an interface. The interface is supposed to be used by people sit behind the computer and looking and manipulating the graph. Something similar to an air traffic controller. So the colourings and appearance of the graph might be changing continuously depending on the number of passengers on trains, number of trains in stations, different colours for different train speeds etc.   
So if you were the coder of the project you will have to reflect all that data into the GUI; a graph representing the above mentioned European rail Network rendered within a Jupyter notebook.

Imagine that you are given the data in two table:
- "stations.xls" -> all the data about the train stations.
- "railconnections.xls" -> all the data about the connections between stations.

The most natural way to work with tabular data in python is using the pandas library. In pandas you can import directly the excel tables into a dataframe.

Note 1: The graph and interface can be deployed with voilà (it is not the purpose of this article to deepen into voilà, you just need to know that there are tools to render, i.e. display, ipycytoscape graphs into a browser outside of a Jupyter notebook.)

Note 2: Ipycytoscape includes already an API that allows to pass a pandas DataFrame to a graph constructor (see here: https://ipycytoscape.readthedocs.io/en/latest/examples/pandas.html). Nevertheless, my approach is slightly different; I would like to show a way to manipulate and change graphs using strictly pandas.

Regarding the data used in this article/notebook I pasted here a dictionary in order for you to be able to follow along without the need of reading an external file and hence the article self-content.

In [1]:
import ipycytoscape
import json
import ipywidgets
import pandas as pd

stations = [{'id': 'BER','country': 'Germany','classes': 'east','label': 'BER Hbf','passengers': 400000},
        {'id': 'MUN','country': 'Germany','classes': 'west','label': 'MUN Hbf','passengers': 200000},
        {'id': 'FRA','country': 'Germany','classes': 'west','label': 'HBf FRA','passengers': 200000},
        {'id': 'HAM','country': 'Germany', 'classes': 'west','label': 'HBf HAM','passengers': 150000},
        {'id': 'LEP','country': 'Germany','label': 'HBf LEP','classes': 'east','passengers': 50000},
        {'id': 'NUR','country': 'Germany','label': 'HBf NUR','classes': 'west','passengers': 50000},
        {'id': 'PAR', 'country': 'France','label': 'PAR CS', 'classes': '', 'passengers': 350000},
        {'id': 'MIL', 'country': 'Italy', 'label': 'MIL CS','classes': '', 'passengers': 250000},
        {'id': 'BAR', 'country': 'Spain', 'label': 'BAR CS','classes': '', 'passengers': 200000},
        {'id': 'LYO', 'country': 'France','label': 'LYO CS','classes': '', 'passengers': 200000}]

stations_df = pd.DataFrame(stations)
stations_df

    id  country classes    label  passengers
0  BER  Germany    east  BER Hbf      400000
1  MUN  Germany    west  MUN Hbf      200000
2  FRA  Germany    west  HBf FRA      200000
3  HAM  Germany    west  HBf HAM      150000
4  LEP  Germany    east  HBf LEP       50000
5  NUR  Germany    west  HBf NUR       50000
6  PAR   France           PAR CS      350000
7  MIL    Italy           MIL CS      250000
8  BAR    Spain           BAR CS      200000
9  LYO   France           LYO CS      200000

And here the file "railconnections.xls".

In [2]:
rail_lines = [{'id': 'line1', 'source': 'BER', 'target': 'MUN', 'speed': '200km/h'},
         {'id': 'line2', 'source': 'MUN', 'target': 'FRA', 'speed': '200km/h'},
         {'id': 'line3', 'source': 'FRA', 'target': 'BER', 'speed': '250km/h'}, 
         {'id': 'line4', 'source': 'BER', 'target': 'HAM', 'speed': '300km/h'}, 
         {'id': 'line5', 'source': 'BER', 'target': 'LEP', 'speed': '300km/h'},
         {'id': 'line6', 'source': 'NUR', 'target': 'LEP', 'speed': '150km/h'}, 
         {'id': 'line7', 'source': 'NUR', 'target': 'FRA', 'speed': '150km/h'},
         {'id': 'line8', 'source': 'BER', 'target': 'PAR', 'speed': '400km/h'}, 
         {'id': 'line9', 'source': 'PAR', 'target': 'LYO', 'speed': '400km/h'}, 
         {'id': 'line10', 'source': 'LYO', 'target': 'BAR', 'speed': '400km/h'},
         {'id': 'line11', 'source': 'LYO', 'target': 'MIL', 'speed': '200km/h'}]
rails_df = pd.DataFrame(rail_lines,columns=['id','source','target','speed'])
rails_df['label'] = rails_df['speed']
rails_df['background-color'] = 'black'
rails_df

        id source target    speed    label background-color
0    line1    BER    MUN  200km/h  200km/h            black
1    line2    MUN    FRA  200km/h  200km/h            black
2    line3    FRA    BER  250km/h  250km/h            black
3    line4    BER    HAM  300km/h  300km/h            black
4    line5    BER    LEP  300km/h  300km/h            black
5    line6    NUR    LEP  150km/h  150km/h            black
6    line7    NUR    FRA  150km/h  150km/h            black
7    line8    BER    PAR  400km/h  400km/h            black
8    line9    PAR    LYO  400km/h  400km/h            black
9   line10    LYO    BAR  400km/h  400km/h            black
10  line11    LYO    MIL  200km/h  200km/h            black

Lets now add the neccesary data to the table. The class of the new stations is 'EU' (look part one and two of this series for understanding classes).    
Every EU rail station should be displayed orange, and the rest of the stations blue, except for the German capital which will be yellow.    
Lets add this data to the DataFrame.

In [3]:
stations_df.loc[stations_df['country'] != 'Germany','classes'] = 'EU'
stations_df['background-color']=''
stations_df.loc[stations_df['country'] == 'Germany','background-color'] = 'blue'
stations_df.loc[stations_df['country'] != 'Germany','background-color'] = 'orange'
stations_df.loc[stations_df['id'] == 'BER','background-color']  = 'yellow'
stations_df

    id  country classes    label  passengers background-color
0  BER  Germany    east  BER Hbf      400000           yellow
1  MUN  Germany    west  MUN Hbf      200000             blue
2  FRA  Germany    west  HBf FRA      200000             blue
3  HAM  Germany    west  HBf HAM      150000             blue
4  LEP  Germany    east  HBf LEP       50000             blue
5  NUR  Germany    west  HBf NUR       50000             blue
6  PAR   France      EU   PAR CS      350000           orange
7  MIL    Italy      EU   MIL CS      250000           orange
8  BAR    Spain      EU   BAR CS      200000           orange
9  LYO   France      EU   LYO CS      200000           orange

The above showed data tables contain the attributes of the stations and rails connections.
A method to pass all this data to ipycytoscape is needed.   

The following method manipulates both tables above in order to output a JSON file that can then be passed to ipycytoscape. The method itself returns the ipycytoscape graph.   
Afterwards it is only necessary to plot it.
The following is a big chunck of code. You DONT NEED TO DIG into it. Just get the idea that the method tranforms two tables with nodes (rail stations) and rail connections (edges) into the real graph.

In [28]:
def transform_into_ipycytoscape(nodes_df,edges_df):
    
    nodes_dict = nodes_df.to_dict('records')
    edges_dict = edges_df.to_dict('records')

    # building nodes

    data_keys = ['id','label','classes']
    position_keys = ['position_x','position_y']
    rest_keys = ['score','idInt','name','score','group','removed','selected','selectable','locked','grabbed'
                 'grabbable']
    
    nodes_graph_list=[]
    for node in nodes_dict:
        dict_node = {}
        data_sub_dict = {'data':{el:node[el] for el in data_keys}}
        rest_sub_dict = {el:node[el] for el in node.keys() if el in rest_keys}
        posi_sub_dict = {}
        if 'position_x' in node.keys() and 'position_y' in node.keys():
            #print(node.keys())
            posi_sub_dict = {'position':{el:node[el] for el in node.keys() if el in position_keys}}
        
        dict_node = {**data_sub_dict,**rest_sub_dict,**posi_sub_dict}
        nodes_graph_list.append(dict_node)
        
    
    # building edges
    
    data_keys  = ['id','source','target']
    data_keys2 = ['label','classes']
    rest_keys  = ['score','weight','group','networkId','networkGroupId','intn','rIntnId','group','removed','selected','selectable','locked','grabbed','grabbable','classes']
    position_keys = ['position_x','position_y']
    
    edges_graph_list = []
    for edge in edges_dict:
        dict_edge = {}
        data_sub_dict = {el:edge[el] for el in data_keys}
        data_sub_dict2 = {el:edge[el] for el in edge.keys() if el in data_keys2}
        rest_sub_dict = {el:edge[el] for el in edge.keys() if el in rest_keys}
        
        dict_edge = {'data':{**data_sub_dict,**data_sub_dict},**rest_sub_dict}
        edges_graph_list.append(dict_edge)
    
    total_graph_dict = {'nodes': nodes_graph_list, 'edges':edges_graph_list}
    
    # building the style
    all_node_style = ['background-color','background-opacity',
                     'font-family','font-size','label','width',
                     'shape','height','width','text-valign','text-halign']
    all_edge_style = ['background-color','background-opacity',
                     'font-family','font-size','label','width','line-color',
                     ]
    
    total_style_dict = {}
    style_elements=[]
    for node in nodes_dict:
        node_dict = {'selector': f'node[id = \"{node["id"]}\"]'}
        style_dict ={"style": { el:node[el] for el in node.keys() if el in all_node_style}}
        node_dict.update(style_dict)
        style_elements.append(node_dict)
    
    for edge in edges_dict:
        edge_dict = {'selector': f'edge[id = \"{edge["id"]}\"]'}
        style_dict ={"style": { el:edge[el] for el in edge.keys() if el in all_edge_style}}
        edge_dict.update(style_dict)
        style_elements.append(edge_dict)
    
    # the graph
    data_graph = json.dumps(total_graph_dict)
    json_to_python = json.loads(data_graph)
    result_cyto = ipycytoscape.CytoscapeWidget()
    result_cyto.graph.add_graph_from_json(json_to_python)    
    result_cyto.set_style(style_elements)    
    
    return result_cyto

G=transform_into_ipycytoscape(stations_df,rails_df)
display(G)

CytoscapeWidget(cytoscape_layout={'name': 'cola'}, cytoscape_style=[{'selector': 'node[id = "BER"]', 'style': …

But I started this article saying that I would show why being able to work directly with tables is a good way to go.   
Now assume that you want to change the colours of the Graph in the following way.  
Stations with more than 200000 passengers should be rendered red and the rest green.  
The high-speed rail lines should be painted red. (high-speed line is considered the one with more or equal than 300km/h)
We can do that operating over the data frame and pass the result again to the ipycytoscape constructor of the method above defined.
Which ones are then the CSS affected attributes? For the nodes is the 'background-color' (we already used it) and for the lines is the 'line-color'.
Let's see.

In [29]:
stations_df['background-color'] = stations_df['passengers'].apply(lambda x: 'red' if x>200000 else 'blue')
rails_df['line-color'] = rails_df['label'].apply(lambda x: 'red' if x in ['400km/h','300km/h'] else 'green')

With only two lines we added the neccesary changes and the dataframes are now as follows.

In [30]:
stations_df

,id,country,classes,label,passengers,background-color,score,width,height
0,BER,Germany,east,BER Hbf,400000,red,1.000000,80.000000,80.000000
1,MUN,Germany,west,MUN Hbf,200000,blue,0.428571,57.142857,57.142857
2,FRA,Germany,west,HBf FRA,200000,blue,0.428571,57.142857,57.142857
3,HAM,Germany,west,HBf HAM,150000,blue,0.285714,51.428571,51.428571
4,LEP,Germany,east,HBf LEP,50000,blue,0.000000,40.000000,40.000000
5,NUR,Germany,west,HBf NUR,50000,blue,0.000000,40.000000,40.000000
6,PAR,France,EU,PAR CS,350000,red,0.857143,74.285714,74.285714
7,MIL,Italy,EU,MIL CS,250000,red,0.571429,62.857143,62.857143
8,BAR,Spain,EU,BAR CS,200000,blue,0.428571,57.142857,57.142857
9,LYO,France,EU,LYO CS,200000,blue,0.428571,57.142857,57.142857

In [31]:
rails_df

,id,source,target,speed,label,background-color,line-color,high-speed,speed_int,score,width
0,line1,BER,MUN,200km/h,200km/h,black,green,[],200,0.2,6.4
1,line2,MUN,FRA,200km/h,200km/h,black,green,[],200,0.2,6.4
2,line3,FRA,BER,250km/h,250km/h,black,green,[],250,0.4,7.8
3,line4,BER,HAM,300km/h,300km/h,black,red,[],300,0.6,9.2
4,line5,BER,LEP,300km/h,300km/h,black,red,[],300,0.6,9.2
5,line6,NUR,LEP,150km/h,150km/h,black,green,[],150,0.0,5.0
6,line7,NUR,FRA,150km/h,150km/h,black,green,[],150,0.0,5.0
7,line8,BER,PAR,400km/h,400km/h,black,red,"[PAR, BER]",400,1.0,12.0
8,line9,PAR,LYO,400km/h,400km/h,black,red,"[LYO, PAR]",400,1.0,12.0
9,line10,LYO,BAR,400km/h,400km/h,black,red,"[BAR, LYO]",400,1.0,12.0
10,line11,LYO,MIL,200km/h,200km/h,black,green,[],200,0.2,6.4

In [32]:
G=transform_into_ipycytoscape(stations_df,rails_df)
display(G)

CytoscapeWidget(cytoscape_layout={'name': 'cola'}, cytoscape_style=[{'selector': 'node[id = "BER"]', 'style': …

### Changing appearance of the edges & nodes with the help of pandas
In order to further illustrate the power of this approach I will add another layout change.
A new security regulation was passed in parliament and all the stations where a high train speed arrives should have special anti-fire measures. So the GUI should show in violet all the stations where at least a high speed train arrives and in green those in which that is not the case.   
Stations in which at least one high speed line arrives

In [33]:
rails_df['high-speed'] = rails_df.apply(lambda x: [x.target,x.source] if x.speed in ['400km/h'] else [], axis=1)

In [34]:
rails_df

,id,source,target,speed,label,background-color,line-color,high-speed,speed_int,score,width
0,line1,BER,MUN,200km/h,200km/h,black,green,[],200,0.2,6.4
1,line2,MUN,FRA,200km/h,200km/h,black,green,[],200,0.2,6.4
2,line3,FRA,BER,250km/h,250km/h,black,green,[],250,0.4,7.8
3,line4,BER,HAM,300km/h,300km/h,black,red,[],300,0.6,9.2
4,line5,BER,LEP,300km/h,300km/h,black,red,[],300,0.6,9.2
5,line6,NUR,LEP,150km/h,150km/h,black,green,[],150,0.0,5.0
6,line7,NUR,FRA,150km/h,150km/h,black,green,[],150,0.0,5.0
7,line8,BER,PAR,400km/h,400km/h,black,red,"[PAR, BER]",400,1.0,12.0
8,line9,PAR,LYO,400km/h,400km/h,black,red,"[LYO, PAR]",400,1.0,12.0
9,line10,LYO,BAR,400km/h,400km/h,black,red,"[BAR, LYO]",400,1.0,12.0
10,line11,LYO,MIL,200km/h,200km/h,black,green,[],200,0.2,6.4

### changing color of nodes
Lets color the with high speed train connections.   
Lets change the color of the stations in the stations dataframe.

In [39]:
stations_high_speed_arriving = rails_df['high-speed'].to_list()
list_of_HS_stations =list(set([item for sublist in stations_high_speed_arriving for item in sublist]))
list_of_HS_stations

['BAR', 'PAR', 'LYO', 'BER']

In [40]:
stations_df['background-color'] = stations_df['id'].apply(lambda x: 'violet' if x in list_of_HS_stations else 'yellow')

In [41]:
G=transform_into_ipycytoscape(stations_df,rails_df)
display(G)

CytoscapeWidget(cytoscape_layout={'name': 'cola'}, cytoscape_style=[{'selector': 'node[id = "BER"]', 'style': …

### changing shapes of nodes
Next the stations with more than 350000 passengers are going to be plotted as squares to differenciate them from the other ones that are smaller.

In [14]:
stations_df['shape'] = stations_df['passengers'].apply(lambda x: 'rectangle' if x>=350000 else '')

In [15]:
stations_df

    id  country classes    label  passengers background-color      shape
0  BER  Germany    east  BER Hbf      400000           violet  rectangle
1  MUN  Germany    west  MUN Hbf      200000           yellow
2  FRA  Germany    west  HBf FRA      200000           yellow
3  HAM  Germany    west  HBf HAM      150000           yellow
4  LEP  Germany    east  HBf LEP       50000           yellow
5  NUR  Germany    west  HBf NUR       50000           yellow
6  PAR   France      EU   PAR CS      350000           violet  rectangle
7  MIL    Italy      EU   MIL CS      250000           yellow
8  BAR    Spain      EU   BAR CS      200000           violet
9  LYO   France      EU   LYO CS      200000           violet

In [17]:
G=transform_into_ipycytoscape(stations_df,rails_df)
display(G)

CytoscapeWidget(cytoscape_layout={'name': 'cola'}, cytoscape_style=[{'selector': 'node[id = "BER"]', 'style': …

### changing the size of the nodes

We want to make the size of the nodes proportional to the amount of passengers of every station.    
In this way the graph will reflect more appropiately the (relative) weight of every station in the whole net.   
If you google for normalizing data you will find that often time the preprocessing library of sklearn is used. In order to not to make things here more complicated a formula will be used without making use of yet another very heavy lybrary.

formula = value / (max_value - min_value)   

Again we can create a column in our nodes dataframe representing the score of every of station.

In [18]:
stations_df['score'] = stations_df['passengers'].apply(lambda x: (x-stations_df['passengers'].min())/(stations_df['passengers'].max()-stations_df['passengers'].min()))

In [19]:
stations_df

,id,country,classes,label,passengers,background-color,shape,score
0,BER,Germany,east,BER Hbf,400000,violet,rectangle,1.000000
1,MUN,Germany,west,MUN Hbf,200000,yellow,,0.428571
2,FRA,Germany,west,HBf FRA,200000,yellow,,0.428571
3,HAM,Germany,west,HBf HAM,150000,yellow,,0.285714
4,LEP,Germany,east,HBf LEP,50000,yellow,,0.000000
5,NUR,Germany,west,HBf NUR,50000,yellow,,0.000000
6,PAR,France,EU,PAR CS,350000,violet,rectangle,0.857143
7,MIL,Italy,EU,MIL CS,250000,yellow,,0.571429
8,BAR,Spain,EU,BAR CS,200000,violet,,0.428571
9,LYO,France,EU,LYO CS,200000,violet,,0.428571

We have a normalized column with the size of the rail stations. if we assume a size of 20px minimun we have to add 20 to the column.

In [20]:
stations_df.drop('shape', axis =1, inplace = True)

In [21]:
stations_df['width'] = stations_df['score'] * 40 + 40
stations_df['height'] = stations_df['score'] * 40 + 40

In [22]:
stations_df

,id,country,classes,label,passengers,background-color,score,width,height
0,BER,Germany,east,BER Hbf,400000,violet,1.000000,80.000000,80.000000
1,MUN,Germany,west,MUN Hbf,200000,yellow,0.428571,57.142857,57.142857
2,FRA,Germany,west,HBf FRA,200000,yellow,0.428571,57.142857,57.142857
3,HAM,Germany,west,HBf HAM,150000,yellow,0.285714,51.428571,51.428571
4,LEP,Germany,east,HBf LEP,50000,yellow,0.000000,40.000000,40.000000
5,NUR,Germany,west,HBf NUR,50000,yellow,0.000000,40.000000,40.000000
6,PAR,France,EU,PAR CS,350000,violet,0.857143,74.285714,74.285714
7,MIL,Italy,EU,MIL CS,250000,yellow,0.571429,62.857143,62.857143
8,BAR,Spain,EU,BAR CS,200000,violet,0.428571,57.142857,57.142857
9,LYO,France,EU,LYO CS,200000,violet,0.428571,57.142857,57.142857

In [24]:
G=transform_into_ipycytoscape(stations_df,rails_df)
display(G)

CytoscapeWidget(cytoscape_layout={'name': 'cola'}, cytoscape_style=[{'selector': 'node[id = "BER"]', 'style': …

The same can be done with the rail connections. The higher the speed the thicker we want to pain the rail connections.

In [25]:
rails_df['speed_int']=rails_df['speed'].str.replace('km/h','').astype('int')
min_speed = rails_df['speed_int'].min()
max_speed = rails_df['speed_int'].max()
span_speed = max_speed-min_speed

rails_df['score'] = rails_df['speed_int'].apply(lambda x: (x-min_speed)/span_speed)

In [26]:
rails_df['width'] = rails_df['score'] *7 +5

In [27]:
G=transform_into_ipycytoscape(stations_df,rails_df)
display(G)

CytoscapeWidget(cytoscape_layout={'name': 'cola'}, cytoscape_style=[{'selector': 'node[id = "BER"]', 'style': …

# Conclusion
It was shown how to use pandas to layout graphs with ipycytoscape in a more direct way taking advance of all the powerful pandas API.